### PR TITLE
fix memory leak on executor creation.

### LINKED ISSUE #110: `LocalExecutor::make_default` leaks memory via RC cycle
The

>And by all I mean, seriously, even spawn_without_executor() failed [ASAN] and there's clearly nothing wrong with that one.

[comment](https://github.com/DataDog/scipio/pull/104#issuecomment-707750633) got me curious, so I decided to `miri` that test.

```
$ MIRI_NIGHTLY=nightly-$(curl -s https://rust-lang.github.io/rustup-components-history/x86_64-unknown-linux-gnu/miri)
$ rustup toolchain add $MIRI_NIGHTLY
$ rustup component add miri --toolchain $MIRI_NIGHTLY
$ export MIRIFLAGS="-Zmiri-disable-isolation"
$ cargo +$MIRI_NIGHTLY miri test -- spawn_without_executor
```

Sure enough, it found a memory leak:

```
   Compiling scipio v0.1.0 (/home/matklad/projects/scipio/scipio)
   Compiling examples v0.0.0 (/home/matklad/projects/scipio/examples)
    Finished test [unoptimized + debuginfo] target(s) in 0.94s
     Running target/x86_64-unknown-linux-gnu/debug/deps/scipio-c56c9e43674a62a8

running 1 test
test executor::test::spawn_without_executor ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 83 filtered out

The following memory was leaked: alloc632956 (Rust heap, size: 168, align: 8) {
    0x00 │ 01 00 00 00 00 00 00 00 01 00 00 00 00 00 00 00 │ ................
    0x10 │ 00 00 00 00 00 00 00 00 08 00 00 00 00 00 00 00 │ ................
    ........................................
    ........................................
alloc633455 (fn: std::intrinsics::drop_in_place::<[closure@scipio/src/executor.rs:455:17: 458:18]> - shim(Some([closure@scipio/src/executor.rs:455:17: 458:18])))
alloc633456 (fn: executor::LocalExecutor::init::{closure#0})
alloc633457 (fn: executor::LocalExecutor::init::{closure#0})
alloc633458 (fn: <[closure@scipio/src/executor.rs:455:17: 458:18] as std::ops::FnOnce<()>>::call_once - shim(vtable))

error: the evaluated program leaked memory

error: aborting due to previous error

error: test failed, to rerun pass '-p scipio --lib'
```

Poking around `closure@scipio/src/executor.rs:455:17: 458:18 ` revealed what seems to an Rc-cycle memory leak. This commit adds a minimal demonstration and a crude fix via weak pointers:

https://github.com/matklad/scipio/commit/9f2912fe544ab46a96196d92959736d9c6350d0e

### PR DESCRIPTION
**Pull request by glommer**
Classic circular reference. The notify function takes a copy of
the shared pointer "queues", but the notify function itself is saved
inside a task queue (which lives inside queues).

Use weak pointers to remove the circularity.

Fixes #110

### What does this PR do?

A brief description of the change being made with this pull request.

### Motivation

What inspired you to submit this pull request?

### Related issues

A list of issues either fixed, containing architectural discussions, otherwise relevant
for this Pull Request.

### Additional Notes

Anything else we should know when reviewing?

### Checklist

[] I have added unit tests to the code I am submitting
[] My unit tests cover both failure and success scenarios
[] If applicable, I have discussed my architecture
[] The new code I am adding is formatted using `rustfmt`

### CODE REVIEW

File: scipio/src/executor.rs [hunk 1]
```diff
@@ -534,6 +534,7 @@ impl LocalExecutor {
     fn init(&mut self) -> io::Result<()> {
         let queues = self.queues.clone();
         let index = 0;
+        let queues_weak = Rc::downgrade(&queues);
```
Comment (matklad) [inline scipio/src/executor.rs:537]: The clone above seems superfluous

Comment (glommer) [reply scipio/src/executor.rs:537]: humm, that looks like the kind of stuff clippy would complain about. It usually complains a lot about clones that are not needed
